-- Load kickstart plugins
require 'plugins.guess-indent'
require 'plugins.nvim-web-devicons'
require 'plugins.gitsigns'
require 'plugins.which-key'
require 'plugins.todo-comments'
require 'plugins.mini'
require 'plugins.lspconfig'
require 'plugins.conform'
require 'plugins.blink-cmp'
require 'plugins.treesitter'
require 'plugins.neo-tree'
require 'plugins.lint'

-- Load additional plugins
require 'plugins.auto-session'
require 'plugins.snacks'
require 'plugins.leap'
require 'plugins.treesitter-textobjects'
require 'plugins.noice'
require 'plugins.zen'
require 'plugins.markdown-toc'
require 'plugins.mkdnflow'
require 'plugins.vimtex'
require 'plugins.scrolleof'
require 'plugins.bufferline'
require 'plugins.lualine'

-- Load additional themes (autoloader)
require 'themes'
