require 'plugins.guess-indent'
require 'plugins.nvim-web-devicons'
require 'plugins.gitsigns'
require 'plugins.which-key'
require 'plugins.todo-comments'
require 'plugins.mini'
require 'plugins.lspconfig'
require 'plugins.conform'
require 'plugins.blink-cmp'
require 'plugins.treesitter'
require 'plugins.treesitter-textobjects'
require 'plugins.lint'

require 'plugins.snacks'
require 'plugins.scope'
require 'plugins.auto-session'
require 'plugins.leap'
require 'plugins.noice'
require 'plugins.markdown-toc'
require 'plugins.mkdnflow'
require 'plugins.vimtex'
require 'plugins.scrolleof'
require 'plugins.bufferline'
require 'plugins.lualine'
require 'plugins.nvim-orgmode'
require 'plugins.window-picker'

require 'themes'
